/**
***                  "Feel Sketch" PMCode Encoder & Decoder.
***    Copyright (C) 2009, Content Idea of ASIA Co.,Ltd. (oss.pmcode@ci-a.com)
***
***    This program is free software: you can redistribute it and/or modify
***    it under the terms of the GNU General Public License as published by
***    the Free Software Foundation, either version 3 of the License, or
***    (at your option) any later version.
***
***    This program is distributed in the hope that it will be useful,
***    but WITHOUT ANY WARRANTY; without even the implied warranty of
***    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
***    GNU General Public License for more details.
***
***    You should have received a copy of the GNU General Public License
***    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_co_cia_pmcode_PMCodeEncoderJNI */

#ifndef _Included_jp_co_cia_pmcode_PMCodeEncoderJNI
#define _Included_jp_co_cia_pmcode_PMCodeEncoderJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_co_cia_pmcode_PMCodeEncoderJNI
 * Method:    encode
 * Signature: ([BILjp/co/cia/pmcode/PMCodeEncoderJNI;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_cia_pmcode_PMCodeEncoderJNI_encode
  (JNIEnv *, jobject, jbyteArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
