/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_co_cia_pmcode_PMCodeEncoderJNI */

#ifndef _Included_jp_co_cia_pmcode_PMCodeEncoderJNI
#define _Included_jp_co_cia_pmcode_PMCodeEncoderJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_co_cia_pmcode_PMCodeEncoderJNI
 * Method:    encode
 * Signature: ([BILjp/co/cia/pmcode/PMCodeEncoderJNI;)I
 */
JNIEXPORT jint JNICALL Java_jp_co_cia_pmcode_PMCodeEncoderJNI_encode
  (JNIEnv *, jobject, jbyteArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
